Cabal-version:       2.2

Name:                codeworld-available-pkgs
Version:             0.1.0.0
License:             Apache-2.0
License-file:        LICENSE
Author:              The CodeWorld Authors
Maintainer:          Chris Smith <cdsmith@gmail.com>
Copyright:           (c) 2020, The CodeWorld Authors
Bug-reports:         https://github.com/google/codeworld/issues

Library
  Build-depends:
    HUnit,
    QuickCheck,
    array,
    base,
    containers,
    text

  Default-language:    Haskell2010

Executable find-dup-modules
  Hs-source-dirs:      src
  Main-is:             Main.hs
  Build-depends:       base,
                       bytestring,
                       containers,
                       ghc-boot

  Default-language:    Haskell2010
