resolver: lts-23.19

packages: 
  - codeworld-account
  - codeworld-api
  - codeworld-auth
  # - codeworld-compiler
  - codeworld-error-sanitizer
  # - codeworld-server
  - codeworld-base

allow-newer: true
allow-newer-deps:
  - ghcjs-base-stub

extra-deps:
  - git: https://github.com/fmidue/ghcjs-base-stub.git
    commit: e19317673d68c2be874fca4661d1ce16b2dc20a1
  - jwt-0.10.1
  - patch-0.0.8.4
  - reflex-0.9.3.3
  - x509-1.7.7
  - x509-store-1.6.9
