user-edited: true
stanzas:
  - type: webapp

    exec: "/opt/codeworld/build/bin/codeworld-server"
    args:
      - --no-access-log

    env:
      LANG: "C.UTF-8"
      LC_ALL: "C.UTF-8"
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/codeworld/build/bin"

    hosts:
      - localhost

    requires-secure: false
